### ISSUE TITLE
XUbuntu 16.04 beta does not run with linux-image-4.4.0-10-generic-tuxonice

### ISSUE THREAD

**Issue by ysalmon** [NigelCunningham/tuxonice-kernel-old#12]
I am currently trying XUbuntu 16.04 beta and the associated tuxonice PPA. Booting the system with linux-image-4.4.0-10-generic-tuxonice leads to a seemingly normal booting sequence, except that when the login screen shows, mouse and keyboard are unresponsive and the system generally freezes.

I was able to run XUbuntu 14.04 with the corresponding tuxonice kernel, although suspending to disk failed roughly 25% of the time when switching the monitor to display the progress bar.

lshw is (excerpt)

```
description: Computer
bits: 64 bits
fonctionnalités: smbios-2.6 vsyscall32
```

  *-core
       description: Motherboard
       identifiant matériel: 0
     *-memory
          description: Mémoire système
          identifiant matériel: 0
          taille: 15GiB
     *-cpu
          produit: Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
          fabriquant: Intel Corp.
          identifiant matériel: 1
          information bus: cpu@0
          taille: 1803MHz
          capacité: 3700MHz
          bits: 64 bits
          fonctionnalités: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid xsaveopt cpufreq
     *-pci
          description: Host bridge
          produit: Xeon E3-1200 Processor Family DRAM Controller
          fabriquant: Intel Corporation
          identifiant matériel: 100
          information bus: pci@0000:00:00.0
          version: 09
          bits: 32 bits
          horloge: 33MHz
          configuration: driver=ie31200_edac
          ressources: irq:0
        *-pci:0
             description: PCI bridge
             produit: Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port
             fabriquant: Intel Corporation
             identifiant matériel: 1
             information bus: pci@0000:00:01.0
             version: 09
             bits: 32 bits
             horloge: 33MHz
             fonctionnalités: pci pm msi pciexpress normal_decode bus_master cap_list
             configuration: driver=pcieport
             ressources: irq:25 portE/S:3000(taille=4096) mémoire:e1400000-e14fffff portE/S:d0000000(taille=268435456)
           *-display
                description: VGA compatible controller
                produit: Redwood XT GL [FirePro V4800]
                fabriquant: Advanced Micro Devices, Inc. [AMD/ATI]
                identifiant matériel: 0
                information bus: pci@0000:01:00.0
                version: 00
                bits: 64 bits
                horloge: 33MHz
                fonctionnalités: pm pciexpress msi vga_controller bus_master cap_list rom
                configuration: driver=radeon latency=0
                ressources: irq:36 mémoire:d0000000-dfffffff mémoire:e1420000-e143ffff portE/S:3000(taille=256) mémoire:e1400000-e141ffff

**Comment by mschlaeffer** [comment]
Do you have the same issue with the original Ubuntu linux-image-4.4.0-10-generic kernel?

**Comment by ysalmon** [comment]
linux-image-4.4.0-10-generic works well.

I noticed a difference in the booting process.
My GRUB is configured to display its menu in text mode, and I also deactivated the fancy splash screen so I can see when the computer switches from text mode to graphic mode.

With the original kernel, this happens early, much of the dmesg log appearing in graphical mode ; with Tuxonice, it only switches when going to display the login prompt (lightdm). This behaviour is the same as what I would get in a regular kernel with the "nomodeset" option.

I have been made aware that the radeon video driver, which I use, can only be started with modeset — if I start a regular kernel with nomodeset, the system defaults to the basic, unaccelerated driver.

There might be a link, although when booting with tuxonice, the graphical display seems correct (the cursor in the lightdm prompt is even blinking for some seconds).

**Comment by mschlaeffer** [comment]
What is the output of `grep modeset /boot/grub/grub.cfg`?
Does it work if you add `modeset` manually to the tuxonice kernel?

**Comment by ysalmon** [comment]
The output indicates that recovery entries contain the nomodeset option while regular entries do not contain any mention of modeset (so modeset seems to be implicit).
I will try with explicit modeset at next boot.

**Comment by ysalmon** [comment]
Explicit modeset did not solve this, but tweaking with my grub parameters allowed me to read more of the boot log on the screen. It appears that some kernel modules failed to load.

Whatever was causing this seems to have been correct because 4.4.0-18-generic-tuxonice
runs fine.

Do you still want to investigate about this now old version ?

**Comment by mschlaeffer** [comment]
No, I think we can close this issue.
