### ISSUE TITLE
Kernel bug at block/blk-core.c:1823 when hibernating with TuxOnIce

### ISSUE THREAD

**Issue by simonbuehler** [NigelCunningham/tuxonice-kernel-old#2]
hi,

don't know on which side it's to be fixed, works with vanilla though:

https://github.com/zfsonlinux/zfs/issues/1237

**Comment by NigelCunningham** [comment]
Sorry for the slow reply - I haven't been receiving notifications of issues from Github. Is this still an issue?

**Comment by simonbuehler** [comment]
can't test as the system is broken curently...
