### ISSUE TITLE
[PATCH] Increase limit for extra pages in kernel config

### ISSUE THREAD

**Issue by hjudt** [NigelCunningham/tuxonice-kernel-old#35]
Since I can't upload the file for a trivial patch and I don't want to push it to github, I put it on pastebin:
https://pastebin.com/My0CZQMr

**Comment by ManuelKrause** [comment]
Can you please add some more info on this?
* What happens to the system, when the limit of "extra pages allowance" is exceeded?
* Is it related to gfx memory or all the system?
I only experience values between 0 - 900 on here, BTW. But your patch maybe useful anyways.

Thx in advance and BR, Manuel Krause

**Comment by hjudt** [comment]
1) I don't know.
2) I do not know for sure, but I believe it is related to drivers in general. However, I suspect mostly gfx drivers are those which need extra pages. My system uses at least 47663 extra pages, sometimes more, which is much more than the max 32768 that you can choose in kernel config without the patch.

**Comment by NigelCunningham** [comment]
Hi guys.

The extra pages allowance is just used for calculating whether we have enough memory free, at the start of preparing the image. Since we can't ask the drivers ahead of time how much memory they will want when we come to the atomic copy, it provides a way for the user to tell ToI instead.

**Comment by hjudt** [comment]
*bump* how about applying this change for tuxonice-head / 4.13?

**Comment by NigelCunningham** [comment]
Applied to 4.13 and HEAD. Apologies for the delay.
